### ISSUE TITLE
MVP backend features

### ISSUE THREAD

**Issue by lukaselflein** [lukaselflein/team-train#1]
General player infrastructure
- [x] create
- [x] delete

Interaction of player with (training-) plan
- [x] view
- [x] claim done, get points

**Comment by lukaselflein** [comment]
Trainer features:
Training
- [ ] create
- [ ] edit
- [ ] view
- [ ] delete
- [ ] assign score

**Comment by lukaselflein** [comment]
Stats features:
- [ ] player current score
- [ ] team current score table
- [ ] player score timeline
- [ ] team score timeline

**Comment by LeviIV** [comment]
role: 
teamcreator

- [ ] invite players

- [ ] assign role (coach/player)

**Comment by LeviIV** [comment]
> Stats features:
> 
> * [ ]  player current score
> * [ ]  team current score table


> * [ ]  player score timeline
> * [ ]  team score timeline

- timeline is non-essential. a valid current value (reduced over time) is more useful.

**Comment by lukaselflein** [comment]
> role:
> teamcreator
> 
> * [ ]  invite players
> * [ ]  kick player
> * [ ]  assign role (coach/player)

I restructured this, roles are now:
Player - do the training
Trainer - create plans
Manager - create teams, kick/invite players

Otherwise, Teamcreator would be a special object which is not a role. If we restrict the number of manager to 1/team, this behaves in the very same way.

**Comment by LeviIV** [comment]
> > role:
> > teamcreator
> > 
> > * [ ]   invite players
> > * [ ]   kick player
> > * [ ]   assign role (coach/player)
> 
> I restructured this, roles are now:
> Player - do the training
> Trainer - create plans
> Manager - create teams, kick/invite players
> 
> Otherwise, Teamcreator would be a special object which is not a role. If we restrict the number of manager to 1/team, this behaves in the very same way.

adjusting view-designs accordingly

**Comment by LeviIV** [comment]
I suggest swapping "trainer" with "Coach". Trainer is not as widely used

**Comment by LeviIV** [comment]
I have added the MVP features to the various views (last comments) - please check for feasibility/time-frame

**Comment by lukaselflein** [comment]
MVP done. Role management is postponed to a later version.
