### ISSUE TITLE
Design: Workouts

### ISSUE THREAD

**Issue by LeviIV** [lukaselflein/team-train#10]
Ticket shows design iterations for the view "WORKOUTS" and lists features

ACCESS: _everyone_

![image](https://user-images.githubusercontent.com/63554475/79136934-1b117100-7db2-11ea-9a0e-2c52df4fb788.png)

**Comment by LeviIV** [comment]
MVP Stage Features

- [ ] ADD WORKOUT BUTTON

- [ ] WORKOUT TITLE

- [ ] WORKOUT POINTS

- [ ] "DONE" BUTTON

- [ ] click on workout opens "EDIT WORKOUT" View

**Comment by lukaselflein** [comment]
Connect button to /claim/<id> api

**Comment by olgamaus** [comment]
- [x] add timer function
