### ISSUE TITLE
Value: Current Fitness

### ISSUE THREAD

**Issue by LeviIV** [lukaselflein/team-train#11]
It'd be interesting to add point value for current fitness. 

A total sum of points doesn't say much about fitness, if people haven't trained in a while.

Use this issue to invent an algorithm

**Comment by LeviIV** [comment]
Simple:

IF SUM[days without training]<=7

THEN [Fitness (today)] = [Fitness (today -1 day)] + [training since yesterday]

ELSE IF SUM[days without training] > 7 AND <= 100
THEN [Fitness (today)] = [Fitness (today - SUM[days without training])] - ([Fitness (today - SUM[days without training])] * 0,003 * SUM[days without training])

ELSE IF SUM[days without training] > 100
THEN [Fitness (today)] = [Fitness (today - SUM[days without training]+100)] - ([Fitness (today - SUM[days without training]+100)] * 0,0015 * SUM[days without training])

UNTIL [Fitness (today)] = 0

**Comment by lukaselflein** [comment]
Let's ask Rene about this, afak there are a few more reliable proxies for fitness.
One is max-rep, which we could squeeze into an advanced version of the training-plans.

> A total sum of points doesn't say much about fitness, if people haven't trained in a while.
Yea, so far I have seen the points more as a gamification/competion thingy than as a good measure of fitness.

**Comment by LeviIV** [comment]
> Yea, so far I have seen the points more as a gamification/competion thingy than as a good measure of fitness.

Yep. But this keeps people on their toes. If you don't add points you'll loose them over time while others keep training. And what a team achieved a year ago shouldn't mean anything for a competition in Motivation

**Comment by lukaselflein** [comment]
>Yep. But this keeps people on their toes.
I don't like discrete time-steps for discounting stuff, but I would be onboard with a decaying function like 
score(t) = score(t_0) * exp(-kt)
Which would make your current score(t) exponentially less than the original score, e.g., a week ago score(t_0). This should motivate you to keep training.
Alternatively, we can jut display a floating average with a decaying window encompassing a few weeks, which should be equivalent.

**Comment by LeviIV** [comment]
I don't mind.
I'd just want the logic to leave the point stable for a week.
Then for the slope to get a bit more dramatic over the next 10-12 weeks and then slow down. 

Should be easy enough for you to implement?

**Comment by lukaselflein** [comment]
will not be implemented in MVP
