### ISSUE TITLE
Design-Choice: Roles

### ISSUE THREAD

**Issue by lukaselflein** [lukaselflein/team-train#2]
We have two roles atm:
* Coach creates plans
* Player practices the exercises

Should we have  
1. one design for each role, with different possible actions
2. or a single design with greyed-out buttons for the invalid actions?

**Comment by LeviIV** [comment]
single design to reduce workload.

- decreases simplicity of design
+ increases shared mental image of UI between roles
+ quicker to design

**Comment by lukaselflein** [comment]
Roles are:
User
Trainer
Manager
