### ISSUE TITLE
Design: Views

### ISSUE THREAD

**Issue by LeviIV** [lukaselflein/team-train#3]
Issue collects the different views necessary for the MVP and their tickets

**Must have:**

- [x] Team Overview #4 

- [x] Team Setup #5 

- [x] Edit Workout  #9 

- [x] Workouts #10 

**Nice to have:**
- [ ] User Score

**Comment by LeviIV** [comment]
Manage Players (teamcreator only)

- [ ] invite players

- [ ] (re-)assign roles

**Comment by LeviIV** [comment]
**Create Workout**
 _(coach only)_

- [ ] free text field for excercise description

- [ ] assign points

- [ ] cancel

- [ ] save

**Comment by LeviIV** [comment]
Personal Score
_(each user)_

- [ ] total score

- [ ] total scores minus time-factor

- [ ] recent exercises & points

**Comment by LeviIV** [comment]
**Team Overview**
_(everyone)_

- [ ] total team score

- [ ] total team score minus time-factor

- [ ] player ranking by total score minus time-factor

**Comment by lukaselflein** [comment]
> Collection of views

What is the idea/context behind this one?

**Comment by lukaselflein** [comment]
Migrated to new issue
