### ISSUE TITLE
description

### ISSUE THREAD

**Issue by LeviIV** [lukaselflein/team-train#41]
Text for a small "about us" page

Success as a sports team often requires all members to put in some additional training between the official sessions. But what should inspire everyone is often unnoticed and the extra motivational boost for the team is lost.

TeamLeap offers a simple way to make ever player's motivation and discipline visible to the other. Design workouts, set weekly team goals and let your players simply tick off their workouts.

TeamLeap IS NOT here to score your fitness. It is about focussing your players spirits and helping them to support and push each other.

Features:

- Design workouts (all kinds possible)

- Assign points to workouts for the required discipline

- set weekly goals

- tick off finished workouts

- show team statistics

- show player activity

**Comment by olgamaus** [comment]
added to About page
